package com.ts.model;

import java.io.Serializable;
import java.util.Date;

public class Banner implements Serializable {
    /**
     *
     */
    private Integer id;

    /**
     *banner路径
     */
    private String src;

    /**
     *链接url
     */
    private String href;

    /**
     *标题
     */
    private String title;

    /**
     *图片类型(1#首页banner,2#资讯轮播图片)
     */
    private Integer type;

    /**
     *排序
     */
    private Integer sort;

    /**
     *删除状态（0未删除，1已删除）
     */
    private Integer delFlg;

    /**
     *创建时间
     */
    private Date createTime;

    /**
     *上次更新时间
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ydj_banner
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public Integer getId() {
        return id;
    }

    /**
     *
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     *banner路径
     */
    public String getSrc() {
        return src;
    }

    /**
     *banner路径
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }

    /**
     *链接url
     */
    public String getHref() {
        return href;
    }

    /**
     *链接url
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     *标题
     */
    public String getTitle() {
        return title;
    }

    /**
     *标题
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     *图片类型(1#首页banner,2#资讯轮播图片)
     */
    public Integer getType() {
        return type;
    }

    /**
     *图片类型(1#首页banner,2#资讯轮播图片)
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *排序
     */
    public Integer getSort() {
        return sort;
    }

    /**
     *排序
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     *删除状态（0未删除，1已删除）
     */
    public Integer getDelFlg() {
        return delFlg;
    }

    /**
     *删除状态（0未删除，1已删除）
     */
    public void setDelFlg(Integer delFlg) {
        this.delFlg = delFlg;
    }

    /**
     *创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *上次更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *上次更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}