package com.ts.model;

import java.io.Serializable;

public class Config implements Serializable {
    /**
     *
     */
    private Long id;

    /**
     *分类
     */
    private String category;

    /**
     *关键字key
     */
    private String keyword;

    /**
     *值
     */
    private String value;

    /**
     *备注
     */
    private String remark;

    /**
     *状态(0#停用,1#启用)
     */
    private Integer status;

    /**
     *排序
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ydj_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public Long getId() {
        return id;
    }

    /**
     *
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *分类
     */
    public String getCategory() {
        return category;
    }

    /**
     *分类
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     *关键字key
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     *关键字key
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     *值
     */
    public String getValue() {
        return value;
    }

    /**
     *值
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     *备注
     */
    public String getRemark() {
        return remark;
    }

    /**
     *备注
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     *状态(0#停用,1#启用)
     */
    public Integer getStatus() {
        return status;
    }

    /**
     *状态(0#停用,1#启用)
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     *排序
     */
    public Integer getSort() {
        return sort;
    }

    /**
     *排序
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}