package com.ts.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     */
    private Long id;

    /**
     *用户名
     */
    private String userName;

    /**
     *手机号
     */
    private String phone;

    /**
     *状态 1  正常   2冻结
     */
    private Byte status;

    /**
     *登录密码
     */
    private String password;

    /**
     *账户余额
     */
    private Long balance;

    /**
     *积分
     */
    private Integer points;

    /**
     *登录token
     */
    private String token;

    /**
     *头像
     */
    private String portrait;

    /**
     *
     */
    private String openId;

    /**
     *是否删除(0#未删除;1#已删除)
     */
    private Byte delFlg;

    /**
     *创建时间
     */
    private Date createTime;

    /**
     *更新时间
     */
    private Date updateTime;

    /**
     *会员等级 0不是会员 10 一级 20 二级  30 三级
     */
    private Byte memberLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ydj_user
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public Long getId() {
        return id;
    }

    /**
     *
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *用户名
     */
    public String getUserName() {
        return userName;
    }

    /**
     *用户名
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     *手机号
     */
    public String getPhone() {
        return phone;
    }

    /**
     *手机号
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     *状态 1  正常   2冻结
     */
    public Byte getStatus() {
        return status;
    }

    /**
     *状态 1  正常   2冻结
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     *登录密码
     */
    public String getPassword() {
        return password;
    }

    /**
     *登录密码
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     *账户余额
     */
    public Long getBalance() {
        return balance;
    }

    /**
     *账户余额
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     *积分
     */
    public Integer getPoints() {
        return points;
    }

    /**
     *积分
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     *登录token
     */
    public String getToken() {
        return token;
    }

    /**
     *登录token
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     *头像
     */
    public String getPortrait() {
        return portrait;
    }

    /**
     *头像
     */
    public void setPortrait(String portrait) {
        this.portrait = portrait == null ? null : portrait.trim();
    }

    /**
     *
     */
    public String getOpenId() {
        return openId;
    }

    /**
     *
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     *是否删除(0#未删除;1#已删除)
     */
    public Byte getDelFlg() {
        return delFlg;
    }

    /**
     *是否删除(0#未删除;1#已删除)
     */
    public void setDelFlg(Byte delFlg) {
        this.delFlg = delFlg;
    }

    /**
     *创建时间
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *创建时间
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *更新时间
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *更新时间
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     *会员等级 0不是会员 10 一级 20 二级  30 三级
     */
    public Byte getMemberLevel() {
        return memberLevel;
    }

    /**
     *会员等级 0不是会员 10 一级 20 二级  30 三级
     */
    public void setMemberLevel(Byte memberLevel) {
        this.memberLevel = memberLevel;
    }
}